I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 104, in script
    c "H-hi??"
KeyError: u'name'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 104, in script
    c "H-hi??"
  File "C:\Users\User\Downloads\renpy-7.1.3-sdk\renpy\ast.py", line 678, in execute
    renpy.exports.say(who, what, interact=self.interact, *args, **kwargs)
  File "C:\Users\User\Downloads\renpy-7.1.3-sdk\renpy\exports.py", line 1229, in say
    who(what, *args, **kwargs)
  File "C:\Users\User\Downloads\renpy-7.1.3-sdk\renpy\character.py", line 1012, in __call__
    who = who_pattern.replace("[who]", sub(who))
  File "C:\Users\User\Downloads\renpy-7.1.3-sdk\renpy\character.py", line 1007, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\User\Downloads\renpy-7.1.3-sdk\renpy\substitutions.py", line 244, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 605, in get_value
KeyError: u'name'

Windows-8-6.2.9200
Ren'Py 7.1.3.1092
The Lab 1.0
Sat Dec 08 23:16:33 2018
